name: Merge

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yaml

    permissions:
      actions: read
      contents: read
      security-events: write

  scorecard:
    uses: ./.github/workflows/scorecard.yaml

    permissions:
      contents: read
      security-events: write
      id-token: write

  release:
    runs-on: ubuntu-latest

    needs:
      - codeql

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          release-type: simple
          command: github-release

  release-pr:
    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      - id: get_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          token: ${{ steps.get_token.outputs.token }}
          release-type: simple
          command: release-pr
