name: Nightly

on:
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch: {}

permissions: read-all

jobs:
  scorecard:
    uses: ./.github/workflows/scorecard.yaml
    permissions:
      contents: read
      security-events: write
      id-token: write

  trunk_upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: get_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: trunk-io/trunk-action/upgrade@35fcebf33a41a29ac3c15098b39451d04ed87e93 # v1.1.2
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          prefix: "deps(trunk-check):"

  codeql:
    uses: ./.github/workflows/codeql.yaml
    permissions:
      actions: read
      contents: read
      security-events: write
