name: Trunk Cache

on:
  push:
    branches:
      - main
    paths:
      - .trunk/trunk.yaml

permissions: read-all

jobs:
  trunk-cache:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: trunk-io/trunk-action@585ad971e85a2a7cc5f62b1468f7bbc7262ef599 # v1.1.3
        with:
          check-mode: populate_cache_only
